package changelog

import (
	"time"

	"github.com/guregu/null/v5"
	"github.com/jonashiltl/openchangelog/internal/domain/source"
)

type Changelog struct {
	// should be generated by repo layer, e.g. IDENTITY COLUMN in pg
	ID          ID
	WorkspaceID string
	Title       string
	Subtitle    string
	Logo        struct {
		Src    null.String
		Link   null.String
		Alt    null.String
		Height null.String
		Width  null.String
	}
	Source    source.Source
	CreatedAt time.Time
}
