package changelog

import (
	"time"

	"github.com/jonashiltl/openchangelog/internal/domain/source"
)

type Changelog struct {
	// should be generated by repo layer, e.g. IDENTITY COLUMN in pg
	ID          ID
	WorkspaceID string
	Title       string
	Subtitle    string
	Logo        struct {
		Src    string
		Link   string
		Alt    string
		Height string
		Width  string
	}
	Source    source.Source
	CreatedAt time.Time
}
