# https://github.com/tonistiigi/xx helpers for cross compilation
FROM --platform=$BUILDPLATFORM tonistiigi/xx AS xx

# Multi-platform build with CGO support
FROM --platform=$BUILDPLATFORM golang:1.24-alpine AS builder

# copy helper scripts
COPY --from=xx / / 
ARG TARGETPLATFORM

RUN apk add clang lld
RUN xx-apk add musl-dev gcc

WORKDIR /build
ENV CGO_ENABLED=1
COPY go.mod .
COPY go.sum .
RUN go mod tidy

COPY . .

ENV CGO_CFLAGS="-D_LARGEFILE64_SOURCE"

RUN xx-go build -buildvcs=false -ldflags "-s -w" -o ./openchangelog cmd/server.go && \
  xx-verify openchangelog

# Build goose binary
FROM --platform=$BUILDPLATFORM golang:1.24 AS goose_builder

WORKDIR /build

# Build goose for target architecture
ARG TARGETOS=linux
ARG TARGETARCH=amd64
ENV GOOS=${TARGETOS}
ENV GOARCH=${TARGETARCH}

RUN git clone https://github.com/pressly/goose && \
    cd goose && \
    go mod tidy && \
    CGO_ENABLED=0 go build -buildvcs=false -ldflags "-s -w -extldflags '-static'" -tags='no_postgres no_redshift no_tidb no_vertica no_ydb no_clickhouse no_mssql no_mysql no_libsql' -o goose ./cmd/goose

FROM alpine

ARG config=i-should-never-exists.jla
# Try to copy config, the * makes sure we don't fail if the file isn't found
COPY *$config /etc/openchangelog.yaml

# Setup our environment to include SQLite. We install ca-certificates
# so we can communicate with external sources over HTTPS.
RUN apk add ca-certificates sqlite
COPY --from=builder /build/openchangelog /app/openchangelog
COPY --from=builder /build/migrations /app/migrations

COPY --from=goose_builder /build/goose/goose /usr/bin/goose

WORKDIR /app
ENTRYPOINT ["/app/openchangelog"]