// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type GhSource struct {
	ID             int64
	WorkspaceID    string
	Owner          string
	Repo           string
	Path           string
	InstallationID int64
}
