// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package store

import (
	"database/sql"
)

type changelog struct {
	ID          string
	WorkspaceID string
	Subdomain   string
	Title       sql.NullString
	Subtitle    sql.NullString
	SourceID    sql.NullString
	LogoSrc     sql.NullString
	LogoLink    sql.NullString
	LogoAlt     sql.NullString
	LogoHeight  sql.NullString
	LogoWidth   sql.NullString
	CreatedAt   int64
	Domain      sql.NullString
}

type changelogSource struct {
	ID             sql.NullString
	WorkspaceID    sql.NullString
	Owner          sql.NullString
	Repo           sql.NullString
	Path           sql.NullString
	InstallationID sql.NullInt64
}

type ghSource struct {
	ID             string
	WorkspaceID    string
	Owner          string
	Repo           string
	Path           string
	InstallationID int64
}

type token struct {
	Key         string
	WorkspaceID string
}

type workspace struct {
	ID   string
	Name string
}
