// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package store

import (
	"database/sql"

	"github.com/jonashiltl/openchangelog/apitypes"
)

type changelog struct {
	ID          string
	WorkspaceID string
	Subdomain   string
	Title       apitypes.NullString
	Subtitle    apitypes.NullString
	SourceID    apitypes.NullString
	LogoSrc     apitypes.NullString
	LogoLink    apitypes.NullString
	LogoAlt     apitypes.NullString
	LogoHeight  apitypes.NullString
	LogoWidth   apitypes.NullString
	CreatedAt   int64
	Domain      apitypes.NullString
}

type changelogSource struct {
	ID             apitypes.NullString
	WorkspaceID    apitypes.NullString
	Owner          apitypes.NullString
	Repo           apitypes.NullString
	Path           apitypes.NullString
	InstallationID sql.NullInt64
}

type ghSource struct {
	ID             string
	WorkspaceID    string
	Owner          string
	Repo           string
	Path           string
	InstallationID int64
}

type token struct {
	Key         string
	WorkspaceID string
}

type workspace struct {
	ID   string
	Name string
}
