name: Build Base Docker Container

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: jonashiltl/openchangelog

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile
            suffix: ""
          - dockerfile: Dockerfile.sqlite
            suffix: "-sqlite"
          - dockerfile: Dockerfile.litefs
            suffix: "-litefs"

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.OPENCHANGELOG_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}${{ matrix.suffix }}
            ${{ matrix.dockerfile == 'Dockerfile' && 'type=raw,value=latest' || '' }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v7
        with:
          file: ${{ matrix.dockerfile }}
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
