name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Run Unit Tests
        run: go run gotest.tools/gotestsum@latest --junitfile unit-tests.xml --format pkgname github.com/jonashiltl/openchangelog/...

      - name: Unit Test Summary
        uses: test-summary/action@v2
        with:
          paths: "unit-tests.xml"
        if: always()

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Run Integration Tests
        run: go run gotest.tools/gotestsum@latest --junitfile integration-tests.xml -- -v ./integration_test.go

      - name: Integration Test Summary
        uses: test-summary/action@v2
        with:
          paths: "integration-tests.xml"
        if: always()